#!/bin/bash
# Show Home icon on the Desktop
# By Ralphy

# Home
if [[ $(xfconf-query --channel xfce4-desktop --property "/desktop-icons/file-icons/show-home") = "false" ]]; then
	xfconf-query --channel xfce4-desktop --property "/desktop-icons/file-icons/show-home" --set "true"
else
	xfconf-query --channel xfce4-desktop --property "/desktop-icons/file-icons/show-home" --set "false"
fi
