#!/bin/bash
# Firewall allow cups 631 printers sharing  
# By Ralphy

# UFW
pkexec ufw delete allow cups && sleep 2 |
zenity --progress --width="280" --auto-close --no-cancel --pulsate \
 	    --title="Firewall - Deny Printers Sharing" --text="✔ Removing printers sharing firewall rules..."
ufw reload